"""rename field user secret totp

Revision ID: d1980f2e1cda
Revises: 52af650722ba
Create Date: 2025-08-24 15:43:56.543496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1980f2e1cda'
down_revision: Union[str, Sequence[str], None] = '52af650722ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tokens_user'), 'tokens', type_='foreignkey')
    op.create_foreign_key('fk_tokens_user', 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('users', sa.Column('totp_secret', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'code_totp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code_totp', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'totp_secret')
    op.drop_constraint('fk_tokens_user', 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tokens_user'), 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
