"""added fernet lib fn

Revision ID: 52af650722ba
Revises: 13d17f923515
Create Date: 2025-08-24 15:34:29.675879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52af650722ba'
down_revision: Union[str, Sequence[str], None] = '13d17f923515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tokens_user'), 'tokens', type_='foreignkey')
    op.create_foreign_key('fk_tokens_user', 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('users', sa.Column('code_totp', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_totp')
    op.drop_constraint('fk_tokens_user', 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tokens_user'), 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
