"""added table backup codes

Revision ID: 8921ae552451
Revises: 714d99fb36d4
Create Date: 2025-08-24 17:10:52.154741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8921ae552451'
down_revision: Union[str, Sequence[str], None] = '714d99fb36d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_codes',
    sa.Column('code', sa.String(length=250), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(extract(epoch from now()) * 1000)::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(extract(epoch from now()) * 1000)::bigint'), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name='fk_backup_codes_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_backup_codes_user_id'), 'backup_codes', ['user_id'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_tokens_user'), 'tokens', type_='foreignkey')
    op.create_foreign_key('fk_tokens_user', 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tokens_user', 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tokens_user'), 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_backup_codes_user_id'), table_name='backup_codes', schema='public')
    op.drop_table('backup_codes', schema='public')
    # ### end Alembic commands ###
