"""added enum token_t value

Revision ID: 3eda49e72b0a
Revises: ef2502ee28cc
Create Date: 2025-08-25 12:40:46.855562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3eda49e72b0a"
down_revision: Union[str, Sequence[str], None] = "ef2502ee28cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_backup_codes_user"), "backup_codes", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_backup_codes_user",
        "backup_codes",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_tokens_user"), "tokens", type_="foreignkey")
    op.create_foreign_key(
        "fk_tokens_user",
        "tokens",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_tokens_user", "tokens", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_tokens_user"),
        "tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_backup_codes_user",
        "backup_codes",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_backup_codes_user"),
        "backup_codes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
