"""add enum val

Revision ID: ef2502ee28cc
Revises: 8e8fbf3174c4
Create Date: 2025-08-25 07:59:50.052019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef2502ee28cc"
down_revision: Union[str, Sequence[str], None] = "8e8fbf3174c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_backup_codes_user"), "backup_codes", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_backup_codes_user",
        "backup_codes",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_tokens_user"), "tokens", type_="foreignkey")
    op.create_foreign_key(
        "fk_tokens_user",
        "tokens",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_tokens_user", "tokens", schema="public", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_tokens_user"),
        "tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_backup_codes_user",
        "backup_codes",
        schema="public",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_backup_codes_user"),
        "backup_codes",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
