"""added table job_applications

Revision ID: 93412613743c
Revises: d64b45ad14b2
Create Date: 2025-09-07 16:46:31.409901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93412613743c'
down_revision: Union[str, Sequence[str], None] = 'd64b45ad14b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('position_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'UNDER_REVIEW', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='application_status_type'), nullable=False),
    sa.Column('date_applied', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('(extract(epoch from now()) * 1000)::bigint'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('(extract(epoch from now()) * 1000)::bigint'), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name='fk_job_applications_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_job_applications_company_name'), 'job_applications', ['company_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_job_applications_user_id'), 'job_applications', ['user_id'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_backup_codes_user'), 'backup_codes', type_='foreignkey')
    op.create_foreign_key('fk_backup_codes_user', 'backup_codes', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_tokens_user'), 'tokens', type_='foreignkey')
    op.create_foreign_key('fk_tokens_user', 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tokens_user', 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tokens_user'), 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_backup_codes_user', 'backup_codes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_backup_codes_user'), 'backup_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_job_applications_user_id'), table_name='job_applications', schema='public')
    op.drop_index(op.f('ix_public_job_applications_company_name'), table_name='job_applications', schema='public')
    op.drop_table('job_applications', schema='public')
    # ### end Alembic commands ###
