"""added column notes to table job_applications

Revision ID: 1ac13e59e515
Revises: 93412613743c
Create Date: 2025-09-07 18:19:12.440215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac13e59e515'
down_revision: Union[str, Sequence[str], None] = '93412613743c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_backup_codes_user'), 'backup_codes', type_='foreignkey')
    op.create_foreign_key('fk_backup_codes_user', 'backup_codes', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('job_applications', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.drop_constraint(op.f('fk_job_applications_user'), 'job_applications', type_='foreignkey')
    op.create_foreign_key('fk_job_applications_user', 'job_applications', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_tokens_user'), 'tokens', type_='foreignkey')
    op.create_foreign_key('fk_tokens_user', 'tokens', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tokens_user', 'tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tokens_user'), 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_job_applications_user', 'job_applications', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_applications_user'), 'job_applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('job_applications', 'notes')
    op.drop_constraint('fk_backup_codes_user', 'backup_codes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_backup_codes_user'), 'backup_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
