"""=> added a many to many relationship company user job

Revision ID: 78354cf5ff3f
Revises: 1abb3d6fd1e1
Create Date: 2025-08-03 09:30:03.292212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78354cf5ff3f'
down_revision: Union[str, Sequence[str], None] = '1abb3d6fd1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_companies_name'), 'companies', ['name'], unique=False, schema='public')
    op.add_column('jobs', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('jobs_user_id_key'), 'jobs', type_='unique')
    op.drop_constraint(op.f('fk_user_id'), 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_job_user_id', 'jobs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_job_company_id', 'jobs', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    op.drop_constraint('fk_job_company_id', 'jobs', schema='public', type_='foreignkey')
    op.drop_constraint('fk_job_user_id', 'jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_id'), 'jobs', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('jobs_user_id_key'), 'jobs', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('jobs', 'company_id')
    op.drop_index(op.f('ix_public_companies_name'), table_name='companies', schema='public')
    op.drop_table('companies', schema='public')
    # ### end Alembic commands ###
