"""added mthod to_d

Revision ID: ff176d533158
Revises: 78354cf5ff3f
Create Date: 2025-08-03 10:41:52.784969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff176d533158'
down_revision: Union[str, Sequence[str], None] = '78354cf5ff3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_job_user_id'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_job_company_id'), 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_job_user_id', 'jobs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_job_company_id', 'jobs', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_job_company_id', 'jobs', schema='public', type_='foreignkey')
    op.drop_constraint('fk_job_user_id', 'jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_company_id'), 'jobs', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('fk_job_user_id'), 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
