"""added car table

Revision ID: 2a20a9d38e54
Revises: ff176d533158
Create Date: 2025-08-03 11:12:45.146910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a20a9d38e54'
down_revision: Union[str, Sequence[str], None] = 'ff176d533158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name='fk_car_user_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('fk_job_user_id'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_job_company_id'), 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_job_user_id', 'jobs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key('fk_job_company_id', 'jobs', 'companies', ['company_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_job_company_id', 'jobs', schema='public', type_='foreignkey')
    op.drop_constraint('fk_job_user_id', 'jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_company_id'), 'jobs', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('fk_job_user_id'), 'jobs', 'users', ['user_id'], ['id'])
    op.drop_table('cars', schema='public')
    # ### end Alembic commands ###
