"""=> 2 migration

Revision ID: daedc8b5f6ae
Revises: 988c28437e6b
Create Date: 2025-08-03 08:19:05.186105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daedc8b5f6ae'
down_revision: Union[str, Sequence[str], None] = '988c28437e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('fk_user_id'), 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_user_id', 'jobs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_id', 'jobs', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_id'), 'jobs', 'users', ['user_id'], ['id'])
    op.drop_table('tests', schema='public')
    # ### end Alembic commands ###
